// <auto-generated />
namespace MMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mms2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mms2));
        
        string IMigrationMetadata.Id
        {
            get { return "201304251352021_mms2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
